---
- name: Install Docker on Amazon Linux 2023
  hosts: webservers
  become: yes
  tasks:
    - name: Install Docker package  
      dnf:
        name: docker
        state: latest

    - name: Start Docker service  
      service:
        name: docker
        state: started
        enabled: yes

    - name: ec2-user ko docker group 
      user:
        name: ec2-user
        groups: docker
        append: yes
